/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#cfe6f2",
        "surface-container-lowest": "#0c0e10",
        "on-secondary-container": "#a6bcc7",
        "background": "#121416",
        "on-tertiary": "#003731",
        "outline-variant": "#414750",
        "tertiary-fixed": "#8df5e4",
        "secondary-container": "#374c56",
        "on-primary": "#003352",
        "surface-container-high": "#282a2c",
        "error": "#ffb4ab",
        "on-primary-container": "#a1d1ff",
        "on-secondary": "#1e333c",
        "primary-fixed": "#cde5ff",
        "surface-container": "#1e2022",
        "on-tertiary-fixed-variant": "#005048",
        "surface-container-low": "#1a1c1e",
        "outline": "#8b919b",
        "surface-container-highest": "#333537",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#94ccff",
        "secondary-fixed-dim": "#b4cad6",
        "surface-variant": "#333537",
        "surface-bright": "#38393c",
        "on-primary-fixed": "#001d32",
        "tertiary-fixed-dim": "#70d8c8",
        "surface-tint": "#94ccff",
        "on-error": "#690005",
        "secondary": "#b4cad6",
        "surface": "#121416",
        "on-background": "#e2e2e5",
        "primary": "#94ccff",
        "inverse-surface": "#e2e2e5",
        "on-surface": "#e2e2e5",
        "tertiary-container": "#006258",
        "surface-dim": "#121416",
        "on-surface-variant": "#c1c7d1",
        "on-primary-fixed-variant": "#004b74",
        "on-tertiary-fixed": "#00201c",
        "inverse-primary": "#006399",
        "on-secondary-fixed-variant": "#354a53",
        "error-container": "#93000a",
        "inverse-on-surface": "#2f3133",
        "primary-container": "#005b8d",
        "tertiary": "#70d8c8",
        "on-secondary-fixed": "#071e27",
        "on-tertiary-container": "#77dece"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
